#ifndef SYSCALL_TABLE_H
#define SYSCALL_TABLE_H

# include "../includes/syscalls.h"
# define MAX_SYSCALL_NUM 329

const struct syscall_entry	syscalls[] = {
	{.name = "read", .nargs = 3, .args = { ARG_INT, ARG_STR, ARG_INT } },
	{.name = "write", .nargs = 3, .args = { ARG_INT, ARG_STR, ARG_INT } },
	{.name = "open", .nargs = 3, .args = { ARG_STR, ARG_INT, ARG_INT } },
	{.name = "close", .nargs = 1, .args = { ARG_INT } },
	{.name = "stat", .nargs = 2, .args = { ARG_STR, ARG_PTR } },
	{.name = "fstat", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "lstat", .nargs = 2, .args = { ARG_STR, ARG_PTR } },
	{.name = "poll", .nargs = 3, .args = { ARG_PTR, ARG_INT, ARG_INT } },
	{.name = "lseek", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "mmap", .nargs = 6, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "mprotect", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "munmap", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "brk", .nargs = 1, .args = { ARG_INT } },
	{.name = "rt_sigaction", .nargs = 4, .args = { ARG_INT, ARG_PTR, ARG_PTR, ARG_INT } },
	{.name = "rt_sigprocmask", .nargs = 4, .args = { ARG_INT, ARG_PTR, ARG_PTR, ARG_INT } },
	{.name = "rt_sigreturn", .nargs = 1, .args = { ARG_INT } },
	{.name = "ioctl", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "pread64", .nargs = 4, .args = { ARG_INT, ARG_STR, ARG_INT, ARG_INT } },
	{.name = "pwrite64", .nargs = 4, .args = { ARG_INT, ARG_STR, ARG_INT, ARG_INT } },
	{.name = "readv", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "writev", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "access", .nargs = 2, .args = { ARG_STR, ARG_INT } },
	{.name = "pipe", .nargs = 1, .args = { ARG_PTR } },
	{.name = "select", .nargs = 5, .args = { ARG_INT, ARG_PTR, ARG_PTR, ARG_PTR, ARG_PTR } },
	{.name = "sched_yield", .nargs = 0, .args = {  } },
	{.name = "mremap", .nargs = 5, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "msync", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "mincore", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "madvise", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "shmget", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "shmat", .nargs = 3, .args = { ARG_INT, ARG_STR, ARG_INT } },
	{.name = "shmctl", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "dup", .nargs = 1, .args = { ARG_INT } },
	{.name = "dup2", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "pause", .nargs = 0, .args = {  } },
	{.name = "nanosleep", .nargs = 2, .args = { ARG_PTR, ARG_PTR } },
	{.name = "getitimer", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "alarm", .nargs = 1, .args = { ARG_INT } },
	{.name = "setitimer", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_PTR } },
	{.name = "getpid", .nargs = 0, .args = {  } },
	{.name = "sendfile64", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "socket", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "connect", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "accept", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_PTR } },
	{.name = "sendto", .nargs = 6, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "recvfrom", .nargs = 6, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_INT, ARG_PTR, ARG_PTR } },
	{.name = "sendmsg", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "recvmsg", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "shutdown", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "bind", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "listen", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "getsockname", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_PTR } },
	{.name = "getpeername", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_PTR } },
	{.name = "socketpair", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "setsockopt", .nargs = 5, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_STR, ARG_INT } },
	{.name = "getsockopt", .nargs = 5, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_STR, ARG_PTR } },
	{.name = "clone", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_PTR, ARG_PTR } },
	{.name = "fork", .nargs = 0, .args = {  } },
	{.name = "vfork", .nargs = 0, .args = {  } },
	{.name = "execve", .nargs = 3, .args = { ARG_STR, ARG_STR, ARG_STR } },
	{.name = "exit", .nargs = 1, .args = { ARG_INT } },
	{.name = "wait4", .nargs = 4, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_PTR } },
	{.name = "kill", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "newuname", .nargs = 1, .args = { ARG_PTR } },
	{.name = "semget", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "semop", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "semctl", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "shmdt", .nargs = 1, .args = { ARG_STR } },
	{.name = "msgget", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "msgsnd", .nargs = 4, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_INT } },
	{.name = "msgrcv", .nargs = 5, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "msgctl", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "fcntl", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "flock", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "fsync", .nargs = 1, .args = { ARG_INT } },
	{.name = "fdatasync", .nargs = 1, .args = { ARG_INT } },
	{.name = "truncate", .nargs = 2, .args = { ARG_STR, ARG_INT } },
	{.name = "ftruncate", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "getdents", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "getcwd", .nargs = 2, .args = { ARG_STR, ARG_INT } },
	{.name = "chdir", .nargs = 1, .args = { ARG_STR } },
	{.name = "fchdir", .nargs = 1, .args = { ARG_INT } },
	{.name = "rename", .nargs = 2, .args = { ARG_STR, ARG_STR } },
	{.name = "mkdir", .nargs = 2, .args = { ARG_STR, ARG_INT } },
	{.name = "rmdir", .nargs = 1, .args = { ARG_STR } },
	{.name = "creat", .nargs = 2, .args = { ARG_STR, ARG_INT } },
	{.name = "link", .nargs = 2, .args = { ARG_STR, ARG_STR } },
	{.name = "unlink", .nargs = 1, .args = { ARG_STR } },
	{.name = "symlink", .nargs = 2, .args = { ARG_STR, ARG_STR } },
	{.name = "readlink", .nargs = 3, .args = { ARG_STR, ARG_STR, ARG_INT } },
	{.name = "chmod", .nargs = 2, .args = { ARG_STR, ARG_INT } },
	{.name = "fchmod", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "chown", .nargs = 3, .args = { ARG_STR, ARG_INT, ARG_INT } },
	{.name = "fchown", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "lchown", .nargs = 3, .args = { ARG_STR, ARG_INT, ARG_INT } },
	{.name = "umask", .nargs = 1, .args = { ARG_INT } },
	{.name = "gettimeofday", .nargs = 2, .args = { ARG_PTR, ARG_PTR } },
	{.name = "getrlimit", .nargs = 1, .args = { ARG_INT } },
	{.name = "getrusage", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "sysinfo", .nargs = 1, .args = { ARG_PTR } },
	{.name = "times", .nargs = 1, .args = { ARG_PTR } },
	{.name = "ptrace", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "getuid", .nargs = 0, .args = {  } },
	{.name = "syslog", .nargs = 3, .args = { ARG_INT, ARG_STR, ARG_INT } },
	{.name = "getgid", .nargs = 0, .args = {  } },
	{.name = "setuid", .nargs = 1, .args = { ARG_INT } },
	{.name = "setgid", .nargs = 1, .args = { ARG_INT } },
	{.name = "geteuid", .nargs = 0, .args = {  } },
	{.name = "getegid", .nargs = 0, .args = {  } },
	{.name = "setpgid", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "getppid", .nargs = 0, .args = {  } },
	{.name = "getpgrp", .nargs = 0, .args = {  } },
	{.name = "setsid", .nargs = 0, .args = {  } },
	{.name = "setreuid", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "setregid", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "getgroups", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "setgroups", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "setresuid", .nargs = 3, .args = { ARG_PTR, ARG_PTR, ARG_PTR } },
	{.name = "getresuid", .nargs = 3, .args = { ARG_PTR, ARG_PTR, ARG_PTR } },
	{.name = "setresgid", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "getresgid", .nargs = 3, .args = { ARG_PTR, ARG_PTR, ARG_PTR } },
	{.name = "getpgid", .nargs = 1, .args = { ARG_INT } },
	{.name = "setfsuid", .nargs = 1, .args = { ARG_INT } },
	{.name = "setfsgid", .nargs = 1, .args = { ARG_INT } },
	{.name = "getsid", .nargs = 1, .args = { ARG_INT } },
	{.name = "capget", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "capset", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "rt_sigpending", .nargs = 2, .args = { ARG_PTR, ARG_INT } },
	{.name = "rt_sigtimedwait", .nargs = 4, .args = { ARG_PTR, ARG_PTR, ARG_PTR, ARG_INT } },
	{.name = "rt_sigqueueinfo", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "rt_sigsuspend", .nargs = 2, .args = { ARG_PTR, ARG_INT } },
	{.name = "sigaltstack", .nargs = 2, .args = { ARG_PTR, ARG_PTR } },
	{.name = "utime", .nargs = 2, .args = { ARG_STR, ARG_PTR } },
	{.name = "mknod", .nargs = 3, .args = { ARG_STR, ARG_INT, ARG_INT } },
	{.name = "uselib", .nargs = 1, .args = { ARG_STR } },
	{.name = "personality", .nargs = 1, .args = { ARG_INT } },
	{.name = "ustat", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "statfs", .nargs = 2, .args = { ARG_STR, ARG_PTR } },
	{.name = "fstatfs", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "sysfs", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "getpriority", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "setpriority", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "sched_setparam", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "sched_getparam", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "sched_setscheduler", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "sched_getscheduler", .nargs = 1, .args = { ARG_INT } },
	{.name = "sched_get_priority_max", .nargs = 1, .args = { ARG_INT } },
	{.name = "sched_get_priority_min", .nargs = 1, .args = { ARG_INT } },
	{.name = "sched_rr_get_interval", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "mlock", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "munlock", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "mlockall", .nargs = 1, .args = { ARG_INT } },
	{.name = "munlockall", .nargs = 0, .args = {  } },
	{.name = "vhangup", .nargs = 0, .args = {  } },
	{.name = "modify_ldt", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "pivot_root", .nargs = 2, .args = { ARG_STR, ARG_STR } },
	{.name = "sctl", .nargs = 1, .args = { ARG_PTR } },
	{.name = "prctl", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "arch_prctl", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "adjtimex", .nargs = 1, .args = { ARG_PTR } },
	{.name = "setrlimit", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "chroot", .nargs = 1, .args = { ARG_STR } },
	{.name = "sync", .nargs = 0, .args = {  } },
	{.name = "acct", .nargs = 1, .args = { ARG_STR } },
	{.name = "settimeofday", .nargs = 2, .args = { ARG_PTR, ARG_PTR } },
	{.name = "mount", .nargs = 5, .args = { ARG_STR, ARG_STR, ARG_STR, ARG_INT, ARG_PTR } },
	{.name = "umount2", .nargs = 2, .args = { ARG_STR, ARG_INT } },
	{.name = "swapon", .nargs = 2, .args = { ARG_STR, ARG_INT } },
	{.name = "swapoff", .nargs = 1, .args = { ARG_STR } },
	{.name = "reboot", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "sethostname", .nargs = 2, .args = { ARG_STR, ARG_INT } },
	{.name = "setdomainname", .nargs = 2, .args = { ARG_STR, ARG_INT } },
	{.name = "iopl", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "ioperm", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "create_module", .nargs = 0, .args = {  } },
	{.name = "init_module", .nargs = 3, .args = { ARG_PTR, ARG_INT, ARG_STR } },
	{.name = "delete_module", .nargs = 2, .args = { ARG_STR, ARG_INT } },
	{.name = "get_kernel_syms", .nargs = 0, .args = {  } },
	{.name = "query_module", .nargs = 0, .args = {  } },
	{.name = "quotactl", .nargs = 4, .args = { ARG_INT, ARG_STR, ARG_INT, ARG_PTR } },
	{.name = "nfsservctl", .nargs = 0, .args = {  } },
	{.name = "getpmsg", .nargs = 0, .args = {  } },
	{.name = "putpmsg", .nargs = 0, .args = {  } },
	{.name = "afs_syscall", .nargs = 0, .args = {  } },
	{.name = "tuxcall", .nargs = 0, .args = {  } },
	{.name = "security", .nargs = 0, .args = {  } },
	{.name = "gettid", .nargs = 0, .args = {  } },
	{.name = "readahead", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "setxattr", .nargs = 5, .args = { ARG_STR, ARG_STR, ARG_PTR, ARG_INT, ARG_INT } },
	{.name = "lsetxattr", .nargs = 5, .args = { ARG_STR, ARG_STR, ARG_PTR, ARG_INT, ARG_INT } },
	{.name = "fsetxattr", .nargs = 5, .args = { ARG_INT, ARG_STR, ARG_PTR, ARG_INT, ARG_INT } },
	{.name = "getxattr", .nargs = 4, .args = { ARG_STR, ARG_STR, ARG_PTR, ARG_INT } },
	{.name = "lgetxattr", .nargs = 4, .args = { ARG_STR, ARG_STR, ARG_PTR, ARG_INT } },
	{.name = "fgetxattr", .nargs = 4, .args = { ARG_INT, ARG_STR, ARG_PTR, ARG_INT } },
	{.name = "listxattr", .nargs = 3, .args = { ARG_STR, ARG_STR, ARG_INT } },
	{.name = "llistxattr", .nargs = 3, .args = { ARG_STR, ARG_STR, ARG_INT } },
	{.name = "flistxattr", .nargs = 3, .args = { ARG_INT, ARG_STR, ARG_INT } },
	{.name = "removexattr", .nargs = 2, .args = { ARG_STR, ARG_STR } },
	{.name = "lremovexattr", .nargs = 2, .args = { ARG_STR, ARG_STR } },
	{.name = "fremovexattr", .nargs = 2, .args = { ARG_INT, ARG_STR } },
	{.name = "tkill", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "time", .nargs = 1, .args = { ARG_PTR } },
	{.name = "futex", .nargs = 6, .args = { ARG_PTR, ARG_INT, ARG_INT, ARG_PTR, ARG_PTR, ARG_INT } },
	{.name = "sched_setaffinity", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "sched_getaffinity", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "set_thread_area", .nargs = 1, .args = { ARG_PTR } },
	{.name = "io_setup", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "io_destroy", .nargs = 1, .args = { ARG_INT } },
	{.name = "io_getevents", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "io_submit", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "io_cancel", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_PTR } },
	{.name = "get_thread_area", .nargs = 1, .args = { ARG_PTR } },
	{.name = "lookup_dcookie", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "epoll_create", .nargs = 1, .args = { ARG_INT } },
	{.name = "epoll_ctl_old", .nargs = 0, .args = {  } },
	{.name = "epoll_wait_old", .nargs = 0, .args = {  } },
	{.name = "remap_file_pages", .nargs = 5, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "getdents64", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "set_tid_address", .nargs = 1, .args = { ARG_PTR } },
	{.name = "restart_syscall", .nargs = 0, .args = {  } },
	{.name = "semtimedop", .nargs = 4, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_PTR } },
	{.name = "fadvise64", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "timer_create", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_PTR } },
	{.name = "timer_settime", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_PTR, ARG_PTR } },
	{.name = "timer_gettime", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "timer_getoverrun", .nargs = 1, .args = { ARG_INT } },
	{.name = "timer_delete", .nargs = 1, .args = { ARG_INT } },
	{.name = "clock_settime", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "clock_gettime", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "clock_getres", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "clock_nanosleep", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_PTR, ARG_PTR } },
	{.name = "exit_group", .nargs = 1, .args = { ARG_INT } },
	{.name = "epoll_wait", .nargs = 4, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_INT } },
	{.name = "epoll_ctl", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "tgkill", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "utimes", .nargs = 2, .args = { ARG_STR, ARG_PTR } },
	{.name = "vserver", .nargs = 0, .args = {  } },
	{.name = "mbind", .nargs = 6, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_PTR, ARG_INT, ARG_INT } },
	{.name = "set_mempolicy", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "get_mempolicy", .nargs = 5, .args = { ARG_PTR, ARG_PTR, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "mq_open", .nargs = 4, .args = { ARG_STR, ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "mq_unlink", .nargs = 1, .args = { ARG_STR } },
	{.name = "mq_timedsend", .nargs = 5, .args = { ARG_INT, ARG_STR, ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "mq_timedreceive", .nargs = 5, .args = { ARG_INT, ARG_STR, ARG_INT, ARG_PTR, ARG_PTR } },
	{.name = "mq_notify", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "mq_getsetattr", .nargs = 2, .args = { ARG_PTR, ARG_PTR } },
	{.name = "kexec_load", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "waitid", .nargs = 5, .args = { ARG_INT, ARG_INT, ARG_PTR, ARG_INT, ARG_PTR } },
	{.name = "add_key", .nargs = 4, .args = { ARG_STR, ARG_STR, ARG_PTR, ARG_INT } },
	{.name = "request_key", .nargs = 4, .args = { ARG_STR, ARG_STR, ARG_STR, ARG_INT } },
	{.name = "keyctl", .nargs = 5, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "ioprio_set", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "ioprio_get", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "inotify_init", .nargs = 0, .args = {  } },
	{.name = "inotify_add_watch", .nargs = 3, .args = { ARG_INT, ARG_STR, ARG_INT } },
	{.name = "inotify_rm_watch", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "migrate_pages", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_PTR, ARG_PTR } },
	{.name = "openat", .nargs = 4, .args = { ARG_INT, ARG_STR, ARG_INT, ARG_INT } },
	{.name = "mkdirat", .nargs = 3, .args = { ARG_INT, ARG_STR, ARG_INT } },
	{.name = "mknodat", .nargs = 4, .args = { ARG_INT, ARG_STR, ARG_INT, ARG_INT } },
	{.name = "fchownat", .nargs = 5, .args = { ARG_INT, ARG_STR, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "futimesat", .nargs = 3, .args = { ARG_INT, ARG_STR, ARG_PTR } },
	{.name = "newfstatat", .nargs = 4, .args = { ARG_INT, ARG_STR, ARG_PTR, ARG_INT } },
	{.name = "unlinkat", .nargs = 3, .args = { ARG_INT, ARG_STR, ARG_INT } },
	{.name = "renameat", .nargs = 4, .args = { ARG_INT, ARG_STR, ARG_INT, ARG_STR } },
	{.name = "linkat", .nargs = 5, .args = { ARG_INT, ARG_STR, ARG_INT, ARG_STR, ARG_INT } },
	{.name = "symlinkat", .nargs = 3, .args = { ARG_STR, ARG_INT, ARG_STR } },
	{.name = "readlinkat", .nargs = 4, .args = { ARG_INT, ARG_STR, ARG_STR, ARG_INT } },
	{.name = "fchmodat", .nargs = 3, .args = { ARG_INT, ARG_STR, ARG_INT } },
	{.name = "faccessat", .nargs = 3, .args = { ARG_INT, ARG_STR, ARG_INT } },
	{.name = "pselect6", .nargs = 6, .args = { ARG_INT, ARG_PTR, ARG_PTR, ARG_PTR, ARG_PTR, ARG_PTR } },
	{.name = "ppoll", .nargs = 5, .args = { ARG_PTR, ARG_INT, ARG_PTR, ARG_PTR, ARG_INT } },
	{.name = "unshare", .nargs = 1, .args = { ARG_INT } },
	{.name = "set_robust_list", .nargs = 2, .args = { ARG_PTR, ARG_INT } },
	{.name = "get_robust_list", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_PTR } },
	{.name = "splice", .nargs = 6, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_PTR, ARG_INT, ARG_INT } },
	{.name = "tee", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "sync_file_range", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "vmsplice", .nargs = 4, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_INT } },
	{.name = "move_pages", .nargs = 6, .args = { ARG_INT, ARG_INT, ARG_PTR, ARG_PTR, ARG_PTR, ARG_INT } },
	{.name = "utimensat", .nargs = 4, .args = { ARG_INT, ARG_STR, ARG_PTR, ARG_INT } },
	{.name = "epoll_pwait", .nargs = 6, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "signalfd", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "timerfd_create", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "eventfd", .nargs = 1, .args = { ARG_INT } },
	{.name = "fallocate", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "timerfd_settime", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_PTR, ARG_PTR } },
	{.name = "timerfd_gettime", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "accept4", .nargs = 4, .args = { ARG_INT, ARG_PTR, ARG_PTR, ARG_INT } },
	{.name = "signalfd4", .nargs = 4, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_INT } },
	{.name = "eventfd2", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "epoll_create1", .nargs = 1, .args = { ARG_INT } },
	{.name = "dup3", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "pipe2", .nargs = 2, .args = { ARG_PTR, ARG_INT } },
	{.name = "inotify_init1", .nargs = 1, .args = { ARG_INT } },
	{.name = "preadv", .nargs = 5, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "pwritev", .nargs = 5, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "rt_tgsigqueueinfo", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "perf_event_open", .nargs = 5, .args = { ARG_PTR, ARG_INT, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "recvmmsg", .nargs = 5, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_INT, ARG_PTR } },
	{.name = "fanotify_init", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "fanotify_mark", .nargs = 5, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "prlimit64", .nargs = 4, .args = { ARG_INT, ARG_INT, ARG_PTR, ARG_PTR } },
	{.name = "name_to_handle_at", .nargs = 5, .args = { ARG_INT, ARG_STR, ARG_PTR, ARG_PTR, ARG_INT } },
	{.name = "open_by_handle_at", .nargs = 5, .args = { ARG_INT, ARG_STR, ARG_PTR, ARG_PTR, ARG_INT } },
	{.name = "clock_adjtime", .nargs = 2, .args = { ARG_INT, ARG_PTR } },
	{.name = "syncfs", .nargs = 1, .args = { ARG_INT } },
	{.name = "sendmmsg", .nargs = 4, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_INT } },
	{.name = "setns", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "getcpu", .nargs = 3, .args = { ARG_PTR, ARG_PTR, ARG_PTR } },
	{.name = "process_vm_readv", .nargs = 6, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_PTR, ARG_INT, ARG_INT } },
	{.name = "process_vm_writev", .nargs = 6, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_PTR, ARG_INT, ARG_INT } },
	{.name = "kcmp", .nargs = 5, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "finit_module", .nargs = 3, .args = { ARG_INT, ARG_STR, ARG_INT } },
	{.name = "sched_setattr", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "sched_getattr", .nargs = 4, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_INT } },
	{.name = "renameat2", .nargs = 5, .args = { ARG_INT, ARG_STR, ARG_INT, ARG_STR, ARG_INT } },
	{.name = "seccomp", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_STR } },
	{.name = "getrandom", .nargs = 3, .args = { ARG_STR, ARG_INT, ARG_INT } },
	{.name = "memfd_create", .nargs = 2, .args = { ARG_STR, ARG_INT } },
	{.name = "kexec_file_load", .nargs = 5, .args = { ARG_INT, ARG_INT, ARG_INT, ARG_STR, ARG_INT } },
	{.name = "bpf", .nargs = 3, .args = { ARG_INT, ARG_PTR, ARG_INT } },
	{.name = "execveat", .nargs = 5, .args = { ARG_INT, ARG_STR, ARG_STR, ARG_STR, ARG_INT } },
	{.name = "userfaultfd", .nargs = 1, .args = { ARG_INT } },
	{.name = "membarrier", .nargs = 2, .args = { ARG_INT, ARG_INT } },
	{.name = "mlock2", .nargs = 3, .args = { ARG_INT, ARG_INT, ARG_INT } },
	{.name = "copy_file_range", .nargs = 6, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_PTR, ARG_INT, ARG_INT } },
	{.name = "preadv2", .nargs = 6, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_INT, ARG_INT, ARG_INT } },
	{.name = "pwritev2", .nargs = 6, .args = { ARG_INT, ARG_PTR, ARG_INT, ARG_INT, ARG_INT, ARG_INT } }
};

#endif
